### ISSUE TITLE
[Feature Request] Route traffic from wlan0 to eth0

### ISSUE THREAD

**Issue by luispedro18** [mattlongman/Hassio-Access-Point#5] opened 2021-02-03 17:28 UTC
It would be cool if the traffic coming in from wlan could go out through eth0 so the devices connected could have internet

**Comment by alameda3piso03** [comment] 2021-07-09 14:48
> It would be cool if the traffic coming in from wlan could go out through eth0 so the devices connected could have internet

I have the same problem too. Is it possible to route the Wi-Fi network traffic to the ethernet network gateway? In other words, the devices connected to the access point have access to the internet through the ethernet.
Thanks in advance

**Comment by mattlongman** [comment] 2021-07-10 21:09
Hi @luispedro18  - apologies for not looking at this sooner (thanks to @alameda3piso03 for bumping it).

I think I've got this working, but could do with help in properly testing it to make sure it's stable.

I've just pushed a version to the dev branch (https://github.com/mattlongman/Hassio-Access-Point/tree/dev/hassio-access-point). Please download and test it out.

New config options:

> Internet access for clients can be enabled with `client_internet_access: '1'`. If DHCP is also enabled, Hassio-Access-Point will try to get the parent host's DNS servers (not just container DNS servers), and serve to clients as part of the DHCP config. This can be overridden with e.g. `client_dns_override: ['1.1.1.1', '8.8.8.8']`. If DHCP is not enabled, `client_internet_access: '1'` will still work, but DNS server(s) will need to be set manually as with the rest of the IP config.

Please update this issue either way, and if it's good, I'll move it to the main branch.

**Comment by luispedro18** [comment] 2021-07-13 12:56
Hi @mattlongman !! First of all, thank you for making the time to address this.. Unfortunately I've changed my setup and I no longer need this... Best to be @alameda3piso03 testing this one...

Again, thank you for doing this 🙌

**Comment by mattlongman** [comment] 2021-07-13 13:41
> Hi @mattlongman !! First of all, thank you for making the time to address this.. Unfortunately I've changed my setup and I no longer need this... Best to be @alameda3piso03 testing this one...
> 
> 
> 
> Again, thank you for doing this 🙌 

It's a feature that you might assume it could do by default, so thanks for the raising the issue in the first place.

Do you mind explaining what your use-case was? I'm curious to find out how this gets used as it's obviously a fairly niche add-on!

**Comment by luispedro18** [comment] 2021-07-13 15:41
My use case was: I wanted to route the traffic from a Roku player through a VPN but since it can't be configured on the device I was trying to get it set up in the Pi (where i have HA installed) and then create a new network to have the Roku connected there.. that way the traffic from Roku would be routed through the VPN 😁

**Comment by pubutil** [comment] 2021-07-15 01:14
Thank you for working on adding internet access to your add-on! 

I tried the dev branch of hassio-access-point and the local network function definitely works as intended. However, with client_internet_access='1' I can't get the AP to provide internet access. DHCP is disabled, but devices are assigned IPs on the 169.254.x.x subnet, instead of grabbing an IP from my router (which is upstream of my Pi, on 192.168.3.x). 

I actually had the same thing happen on Raspberry Pi OS, which is why I tried moving to Hass.io: hostapd worked as intended, until I installed the Home Assistant Docker container. After adding the Docker container the client IPs didn't match with my local network and clients all lost internet access. 

It's possible I'm doing something wrong, though! Here's my config if it helps (SSID/passphrase removed):

```
ssid: ssid
wpa_passphrase: passphrase
channel: '11'
address: 192.168.3.139
netmask: 255.255.255.0
broadcast: 192.168.3.254
interface: wlan0
hide_ssid: '0'
dhcp: '0'
dhcp_start_addr: ''
dhcp_end_addr: ''
allow_mac_addresses: []
deny_mac_addresses: []
debug: 0
hostapd_config_override: []
client_internet_access: '1'
client_dns_override:
  - 9.9.9.9
  - 149.112.112.112
```

Here's the initial part of my log as well (SSID/MAC address removed). I'm not experienced enough to know whether the rfkill and wlan0 errors are significant, seeing as local network access still works as intended:

> Starting Hass.io Access Point Addon
> Configuration file: /hostapd.conf
> rfkill: Cannot open RFKILL control device
> wlan0: Could not connect to kernel driver
> Using interface wlan0 with hwaddr 00:00:00:00:00:00 and ssid "ssid"
> wlan0: interface state UNINITIALIZED->ENABLED
> wlan0: AP-ENABLED  

Following this were a few associations/disassociations/handshakes that I didn't include.

I hope this helps! Let me know if you need more info/testing from me.

**Comment by mattlongman** [comment] 2021-07-15 07:57
Hi @pubutil - thanks for testing!

The host network doesn't see each individual device connecting to the Pi, it just sees all requests as coming from the Pi, so responds accordingly, then the Pi sends responses out to the appropriate client.

For your example:

> address: 192.168.3.139
> netmask: 255.255.255.0
> broadcast: 192.168.3.254
> dhcp: '0'

You would manually need to set the IP on the client device as DHCP is off, and the client can't request an IP from the parent network/DHCP server (because the parent network just sees the Pi).

Similarly, you would also need to manually set the DNS servers when manually IPing the device.

> client_dns_override:
>    - 9.9.9.9
>    - 149.112.112.112

The `client_dns_override` option can be used where the Pi is unable to determine DNS servers from the parent network, or you just wanted to use different DNS for clients connected to Hass.io Access Point, but there's no way of setting DNS on a client without DHCP.

Do you need clients to be accessible/visible from the parent network? Could you explain what your use-case is?

One thing I'm going to explore is what's required to configure this as a bridged access point (where clients are visible to the host network, which I think is what you were expecting with this current version) and see if it can be added as an option.

**Comment by mattlongman** [comment] 2021-07-16 08:08
Related issue: [bridged ap](https://github.com/mattlongman/Hassio-Access-Point/issues/8)

**Comment by shageman** [comment] 2021-07-23 20:59
My use-case is this. This is for a mobile use case (think RV, van, or boat) I intend to have two pis connected via ethernet:

* pi 1 runs home assistant OS (and has a zigbee dongle, etc) - I want to make this a wifi access point too so I can connect wifi enabled devices to this network directly
* pi 2 runs a raspbian OS and by default shows a touch panel view of the home assistant dashboard. This pi's wifi has a bunch of wifi networks programmed that the vehicle passes by relatively often to allow the entire system to gain internet access temporarily without uninstalling / reinstalling. For that it shares the wifi connection with the rest of the network

**Comment by shageman** [comment] 2021-07-23 21:02
BTW, this config works for me

```
ssid: SSID
wpa_passphrase: PW
channel: '6'
address: 192.168.99.1
netmask: 255.255.255.0
broadcast: 192.168.99.255
interface: wlan0
hide_ssid: '0'
dhcp: '1'
dhcp_start_addr: 192.168.99.10
dhcp_end_addr: 192.168.99.20
allow_mac_addresses: []
deny_mac_addresses: []
debug: 0
hostapd_config_override: []
client_internet_access: '1'
client_dns_override:
  - 1.1.1.1
```

**Comment by discrockers** [comment] 2022-03-01 11:04
Hello,

I am a newbie with Home Assistant. I just discovered it and already lovin it! :slight_smile:
I installed the [Hass.io 2](http://hass.io/) Access Point on a Raspberry 4 and would like to use it in “bridge mode” like I did with RaspAp before. I can setup the WiFi and it is available, but when I try to connect my iPhone it couldn’t get an IP address. As soon as I activate the DHCP it works.

What I am doing wrong. I tought deactiveate the DHCP the DHCP server inside my network is used to get the IPs for the connected Accesspoint devices. I am using a FritzBox 4970 and eBlocker as DHCP server to filter ads and unwanted stuff.

Any Idea would be helpful. Thank you
Kind regards
D-Rock

**Comment by teranus** [comment] 2022-06-07 10:03
Is it still necesary to use the dev branch for internet routing from wlan0 to eth0 or is it now enough tested and in the main branch?
I need exactly that function and am just about to implement this addon.
As here was no further discussion since over a year, maybe it is implemented already?

**Comment by mattlongman** [comment] 2022-06-07 11:24
> Is it still necesary to use the dev branch for internet routing from wlan0 to eth0 or is it now enough tested and in the main branch? I need exactly that function and am just about to implement this addon. As here was no further discussion since over a year, maybe it is implemented already?

Not necessary to use dev branch. It was merged [here](https://github.com/mattlongman/Hassio-Access-Point/commit/c1c4a8b36fcb856521ec4bbfc1d18d610acdb673)

I'm planning to go through and clear some of these issues soon, but if you have an interest in this addon and could help with maintaining it, please let me know (I don't use it myself at the moment, and don't have the capability to test it currently).

**Closed by mattlongman** 2022-06-07 11:24 UTC
Labels: enhancement

**Comment by stegno** [comment] 2022-08-06 14:14
I am also looking for way to do a bridged dumb AP, since its done, AP could be a part of wifi coverage within home (if same SSID and security) with normal roaming between other APs. Now clients have and reinit wifi connection to change IPs and gateways, so data transmitting stops for a much more time..

**Comment by dingausmwald** [comment] 2022-11-25 04:47
Sorry to bump this, and thanks for this awesome addon.
Little question: All are talking about linking wlan0 to eth0. Is it possible to share the internet connection from a usb wifi dongle to wlan0?

In addition, dont know if related, i get this in logs now and cant set my network config anymore (connection still works)

/network/info return code 500

and

Failed to to call /network/info -

**Comment by walle2603** [comment] 2023-03-01 10:10
Hi, i am really happy about the AP function, it works fine using wlan0 to eth0. Currently I am looking for a solution routing the traffic from wlan0 to wlan1 (external USB Wifi Adapter). Unfortunately it doesen't work. I thing its the same topic like @dingausmwald. Any options to make it work or to add that feature?

Thanks in advanced

**Comment by dingausmwald** [comment] 2023-03-01 11:48
This feature request is closed.
Anyway, you can use my fork, i implemented the feature there.
https://github.com/dingausmwald/Hassio-Access-Point
be aware that i had to change ht_capab=[HT40][SHORT-GI-20][DSSS_CCK-40]
to
ht_capab=[HT40][SHORT-GI-20] in hostapd.conf since my additional [wifi usb stick](https://www.amazon.de/gp/product/B073J3HXZH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) does not support [DSSS_CCK-40] and "hostapd_config_override" option does not seem to work

you can add this by going to your home assistant / addons / add-on store / 3 dots / repositories / and add the github link of my fork there.

My interface (the wifi stick my 20+ tasmota plugs are connected to) is wlp1s0u1u4u3 and my client_internet_access_interface is wlan0, since the wifi from raspi4 cant handle more than 8? connections.
