### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by ledhed-jgh** [mattlongman/Hassio-Access-Point#27] opened 2022-05-14 16:09 UTC
After updating to Home Assistant 2022.5, starting this add-on fails and throws this error in the logs:
`s6-overlay-suexec: fatal: can only run as pid 1`

It looks like you may need to change some permissions and/or update the AppArmor profile.

S6-Overlay 3.x update on our docker base images:
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Thanks.

**Comment by askmurphy** [comment] 2022-05-27 18:01
I can confirm that, s6-overlay-suexec: fatal: can only run as pid 1 problem...  Add-on doesn't work..

**Comment by olaldiko** [comment] 2022-06-02 09:37
I solved it on #28. It hasn't been merged yet. You can point to my repo in the meantime.

**Comment by liroman2312** [comment] 2022-06-02 11:18
How can I do thise please explain

**Comment by olaldiko** [comment] 2022-06-02 14:18
On home assistant, instead of pointing to @mattlongman 's repo to install the addon, point to mine: https://github.com/olaldiko/Hassio-Access-Point.git
You have instructions to do so here: https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons

**Comment by mattlongman** [comment] 2022-06-02 23:15
> I solved it on #28. It hasn't been merged yet. You can point to my repo in the meantime.

@olaldiko - Thank you for the PR. Merged.

I'm not particularly familiar with hostapd (other than what I got working for this project when I was using it myself). I'm looking for someone(s) that understands it a bit better, who might be interested in assisting on some issues/PRs.

I'll try to update all of the issues with a similar note, but if you're interested, please let me know.

**Comment by liroman2312** [comment] 2022-06-05 19:21
> On home assistant, instead of pointing to @mattlongman 's repo to install the addon, point to mine: https://github.com/olaldiko/Hassio-Access-Point.git You have instructions to do so here: https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons

Hi I manged to install i am using supervised on debian with ac600 wifi adapter when I tried to lunch i get on the log no kenral driver founed and it's shut down what can I do ?

**Comment by liroman2312** [comment] 2022-06-06 07:52
With the hist it works great I can connect to wifi and all but with you're addon it gives error what can I do

**Comment by olaldiko** [comment] 2022-06-07 07:27
It has to do more with an incompatibility issue with hostapd than with the addon itself. Send us the logs of the addon so we can have a look.
I would also try to create a wifi hotspot on the host itself since it is a full-fledged system. That way we can discard that the issue is on the addon.

**Comment by liroman2312** [comment] 2022-06-07 08:09
Well I tried now the hostapd package on my debian and its running good I will try thise to if it work and maybe you will find qn option to run thise package form homeassistant itself and also I will try to give you the log soon

**Comment by askmurphy** [comment] 2022-06-07 08:36
Great!

**Closed** 2022-06-17 20:54 UTC
